app/build.gradle.kts
app/src/main/java/com/nbcamp_14_project/detail/DetailActivity.kt
app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
app/src/main/java/com/nbcamp_14_project/home/Home.kt
app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
app/src/main/res/anim/slide_in_up.xml
app/src/main/res/anim/slide_out_down.xml
app/src/main/res/anim/stay.xml

[FEAT] : DetailActivity 원문 보기 , 애니매이션 기능

---

.idea/compiler.xml
.idea/gradle.xml
.idea/misc.xml
app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
app/src/main/java/com/nbcamp_14_project/data/model/User.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
app/src/main/res/drawable/et_border_radius.xml
app/src/main/res/drawable/et_border_radius_red.xml
app/src/main/res/layout/activity_sign_up.xml

[FEAT]: googlelogin 구현

---

app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt

[FEAT] : Login과 FavoriteFragment Firestore 연결

---

app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
app/src/main/res/drawable/category_dialog.xml

회원가입할때 파이어 스토어에 정보가 저장되게 구현하였습니다.

[FEAT]: 회원가입시 파이어스토어에 정보 저장

---

app/build.gradle.kts
app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
app/src/main/res/layout/fragment_favorite.xml
build.gradle.kts

[FEAT] : FavoriteFragment Login기능 구현

---

app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt

[FEAT] : FavoriteFragment Login, Logout 기능 구현, Login시 이름 데이터 받기

---

app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt

[Feat]: 회원가입 유효성 검사

---

app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt

비밀번호 textwatcher의 text를 변경했습니다.

[Fix]: 회원가입 유효성검사 수정

---

app/src/main/res/values/themes.xml

[FIX]: 테마수정

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nbcamp_14_project/SplashActivity.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
app/src/main/res/drawable/btn_white_border.xml
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/fragment_favorite.xml
build.gradle.kts

[DESIGN] : Splash 화면 추가

---

app/src/main/java/com/nbcamp_14_project/SplashActivity.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
app/src/main/res/drawable/iv_home.xml

[Fix] :구글 로그인 시 FavoriteFragment에 바로 적용 안되는거 수정

---

app/src/main/res/layout/activity_splash.xml

[Fix] :Splash UI 수정

---

.idea/deploymentTargetDropDown.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
app/src/main/res/drawable/et_border_radius.xml
app/src/main/res/drawable/et_border_radius_green.xml
app/src/main/res/drawable/et_border_radius_red.xml
app/src/main/res/drawable/et_round_black.xml
app/src/main/res/drawable/ic_signup_check.xml
app/src/main/res/drawable/signup_scroll_top_outline.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

[FIX]: 피드백 한 부분 수정

---

app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt

[FIX] : DebateFragment에 Firestore 적용

---

app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
app/src/main/java/com/nbcamp_14_project/data/model/User.kt
app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/fragment_category.xml

회원가입 하면 선택한 카테고리가 파이어스토어에 전달 되게 하였습니다.

[FEAT]: 이메일 로그인 시 카테고리 전달

---

app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateViewModel.kt

[FEAT] : DebateDetailFragment 댓글 기능 구현

---

app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/res/layout/fragment_debatedetail.xml

[FIX] : DebateDetailFragment 찬성, 반대 기능 수정

---

app/src/main/java/com/nbcamp_14_project/debate/Comment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailItem.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/res/drawable/agree_button_stroke.xml
app/src/main/res/drawable/iv_debate2.xml
app/src/main/res/drawable/opposite_button_stroke.xml
app/src/main/res/layout/dialog_debatedetail.xml
app/src/main/res/layout/fragment_debate.xml
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/layout/item_debatedetail2.xml
app/src/main/res/values/colors.xml

[FEAT] : DebateDetailFragment 댓글 추가시 찬반 선택기능

---

app/build.gradle.kts
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
app/src/main/res/drawable/ic_more.xml
app/src/main/res/drawable/spinner_selector.xml
app/src/main/res/layout/dialog_debate.xml
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/values/strings.xml

[FEAT] : DebateDetailFragment Spinner 기능 구현

---

app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/res/drawable/ic_minus_24px.xml
app/src/main/res/drawable/ic_plus.xml
app/src/main/res/drawable/iv_debate3.xml
app/src/main/res/layout/fragment_debate.xml
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/layout/item_debate.xml
app/src/main/res/layout/item_debatedetail.xml

[DESIGN] : DebateFragment UI 수정

---

.idea/misc.xml
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateViewModel.kt
app/src/main/res/layout/dialog_debate.xml
app/src/main/res/layout/fragment_debate.xml
app/src/main/res/layout/fragment_debate_plus.xml
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/layout/item_debate.xml
app/src/main/res/values/dimens.xml

[DESIGN] : DebateFragment, DebateDetailFragment UI 수정

---

app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
app/src/main/res/drawable/dialog_background.xml
app/src/main/res/drawable/dialog_rounded_bg.xml
app/src/main/res/drawable/et_round_white2.xml
app/src/main/res/drawable/ic_blue.xml
app/src/main/res/drawable/ic_red.xml
app/src/main/res/layout/activity_sign_up.xml
app/src/main/res/layout/dialog_debate.xml
app/src/main/res/layout/fragment_debate.xml
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/layout/item_debate.xml
app/src/main/res/layout/item_debatedetail.xml
app/src/main/res/layout/item_debatedetail2.xml
app/src/main/res/values/style.xml

[FEAT] : DebateFragment 검색 기능 구현

---

app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteRepositiory.kt
app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
app/src/main/res/layout/activity_sign_up.xml

기자 팔로잉 기능 onResume()에서 onViewCreated로 이동했고 피드백에 맞게 UI수정 했습니다.

기자 팔로잉 기능 수정, favorite ui 수정

---

.idea/deploymentTargetDropDown.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/values-560dpi/dimens.xml
app/src/main/res/values-xhdpi/dimens.xml

[FIX] : Splash 화면 변경 및 dimens 추가

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
app/src/main/res/layout/fragment_debatedetail.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/layout/fragment_search_item.xml

[FIX] : 주석처리 및 SearchFragment UI 수정
